---
# https://yamllint.readthedocs.io/en/stable/rules.html#

extends: default

locale: en_US.UTF-8

ignore: |
  ../../vendor/
  ../../node_modules/
  *.template.yaml

rules:
  indentation: enable
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
