---
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ci-pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   #        ┌───────────── minute (0 - 59)
  #   #        │  ┌───────────── hour (0 - 23)
  #   #        │  │ ┌───────────── day of the month (1 - 31)
  #   #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #   #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #   #        │  │ │ │ │
  #   #        │  │ │ │ │
  #   #        │  │ │ │ │
  #   #        *  * * * *
  #   - cron: "30 1 * * 0"

jobs:
  validate:
    if: ${{ always() }}
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Validate
        run: |
          make setup/validate
      - name: Validate Codebase
        run: |
          make lint/ci
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: validate-log-artifact
          path: analyzer/**/*.log
          retention-days: 1

  release:
    if: ${{ always() }}
    needs: [validate]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Release
        run: |
          make setup/release
      - name: Release Codebase
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
