---
name: Continuous Integration

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  integration:
    if: ${{ always() }}
    name: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Validate
        run: |
          make setup/validate

      - name: Validate Codebase
        run: |
          make lint/ci
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: validate-log-artifact
          path: analyzer/**/*.log
          retention-days: 1
